### ISSUE TITLE
WiFiがONでもOFFでも、コロンが点滅するようにしたい(from takao)

### ISSUE THREAD

**Issue by ytani01** [ytani01/NixieClock#6]
現在の動作は、WiFiがONのときは、コロンが点滅するが、OFFのときは点滅しない(点灯のみ)。
両方とも点滅するようにしたい (from takao)

**Comment by ytani01** [comment]
4桁版では、時刻表示のときは、両方とも点滅するが、日付表示のときに、WiFiがONの場合は点滅/OFFの場合は点灯するようにした。

**Comment by ytani01** [comment]
> 4桁版では、時刻表示のときは、両方とも点滅するが、日付表示のときに、WiFiがONの場合は点滅/OFFの場合は点灯するようにした。

6桁版でも、同じ仕様にした。

**Comment by ytani01** [comment]
高尾くんがOKならクローズしてください。

**Comment by minori24** [comment]
OKです。Closeお願いします
