### ISSUE TITLE
バックライトはデフォルトでOFFにしたい(from takao)

### ISSUE THREAD

**Issue by ytani01** [ytani01/NixieClock#7]
バックライトのフルカラーLEDは、デフォルトでは、OFFにしたい(from takao)

**Comment by ytani01** [comment]
BTN2(明るさ変更と同じボタン)をダブルクリックで、バックライトをON/OFFするようにした。

**Comment by ytani01** [comment]
高尾くんが確認してクローズしてください。

**Comment by minori24** [comment]
OKです。Closeお願いします
